### ISSUE TITLE
Description of item not displaying in Edit page

### ISSUE THREAD

**Issue by Nandusss** [Nandusss/COMP-229-BackEnd-Group-3#17]
For any items the description(bodyDesc) is not displaying properly in the textfield. There appears to be bunch of white spaces every time edit/add page is open. values from database is being retrieved without issue, only issue is with the displaying it in text field.
![issue](https://user-images.githubusercontent.com/113753010/201443239-0b9651a6-b68b-4ddb-988a-5c8ddd18ee73.jpg)

**Comment by Nandusss** [comment]
Issue was with the value attribute. Text area doesn't have one. Fixed the displaying issue. White space issue still not solved.

**Comment by Nandusss** [comment]
white space issue caused by the spaces that was present in the code itself. Fixed

**Comment by akomarzx** [comment]
Good Job Nandu!
